version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  catalogo.api:
    container_name: catalogo.api
    environmet:
      - APSNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
