apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: catalogoapi
  labels:
    app: catalogoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogoapi
  template:
    metadata:
      labels:
        app: catalogoapi
    spec:
      containers:
      - name: catalogoapi
        image: microsservices-catalogoapi:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Deployment"
          - name: Mongo__ConnectionString
            value: "mongodb://mongo:27017"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

